# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

ingredient_list = [
 [ "chicken breast", 7.99 ],
 [ "potato", 1.29 ],
 [ "chicken broth", 3.59 ],
 [ "water", 0.00 ],
 [ "curry powder", 4.29 ],
 [ "mixed vegetables", 4.29 ],
 [ "cornstarch", 2.89 ],
 [ "olive oil", 9.49 ],
 [ "red onion", 1.99 ],
 [ "salt", 0.89 ],
 [ "bay leaf", 2.69 ],
 [ "turmeric", 3.09 ],
 [ "chili powder", 7.49 ],
 [ "paprika", 7.89 ],
 [ "ground ginger", 3.59 ],
 [ "minced garlic", 4.09 ],
 [ "tomato", 1.39 ],
 [ "white sugar", 4.09 ],
 [ "cardamom pod", 12.55 ],
 [ "whole cloves", 25.00 ],
 [ "cinnamon stick", 8.69 ],
 [ "ghee", 5.49 ],
 [ "ground coriander", 6.49 ],
 [ "cilantro", 2.49 ],
 [ "vegetable oil", 4.39 ],
 [ "white onion", 1.79 ],
 [ "garlic cloves", 0.89 ],
 [ "cauliflower", 4.99 ],
 [ "garlic salt", 6.29 ],
 [ "unsweetened coconut milk", 3.59 ],
 [ "chicken stock", 2.69 ],
 [ "curry paste", 4.79 ],
 [ "coconut milk", 3.89 ],
 [ "fish sauce", 5.29 ],
 [ "brown sugar", 1.69 ],
 [ "chicken thighs", 4.99 ],
 [ "frozen peas", 3.89 ],
 [ "green bell pepper", 1.59 ],
 [ "carrot", 1.99 ],
 [ "pineapple", 5.99 ],
 [ "mayonnaise", 4.89 ],
 [ "chili oil", 6.19 ],
 [ "chunk chicken", 3.49 ],
 [ "garam masala", 5.29 ],
 [ "garlic powder", 7.59 ],
 [ "onion", 0.69 ],
 [ "cream of chicken soup", 1.19 ],
 [ "golden raisins", 4.59 ],
 [ "peanut oil", 5.19 ],
 [ "croissants", 8.59 ],
 [ "chutney", 5.89 ],
 [ "lettuce", 1.99 ],
 [ "chicken bullion", 1.59 ],
 [ "mushrooms", 2.59 ],
 [ "elbow macaroni", 1.89 ],
 [ "sour cream", 2.19 ],
 [ "black olives", 1.49 ],
 [ "apple", 0.79 ],
 [ "yellow bell pepper", 2.49 ],
 [ "celery", 4.99 ],
 [ "green curry paste", 4.79 ],
 [ "lime", 0.99 ],
 [ "green onions", 0.99 ],
 [ "russet potatoes", 3.49 ],
 [ "flour", 3.29 ],
 [ "milk", 3.99 ],
 [ "eggs", 4.09 ],
 [ "butter", 4.39 ],
 [ "parmesan cheese", 6.59 ],
 [ "chopped pecans", 10.19 ],
 [ "grapes", 8.99 ],
 [ "chicken drumsticks", 2.79 ],
 [ "apricot nectar", 4.89 ],
 [ "dried apricots", 3.79 ],
 [ "chile pepper", 1.59 ],
 [ "water chestnuts", 1.99 ],
 [ "cayenne pepper", 1.19 ],
 [ "cumin", 6.49 ],
 [ "jasmine rice", 5.39 ],
 [ "red curry paste", 4.79 ],
 [ "bamboo shoots", 2.19 ],
 [ "pineapple chunks", 2.19 ],
 [ "soy sauce", 4.99 ],
 [ "cider vinegar", 2.59 ],
 [ "minced ginger", 3.09 ],
 [ "ginger root", 4.99 ],
 [ "ginger", 4.99 ],
 [ "mango", 2.49 ],
 [ "artichoke hearts", 4.09 ],
 [ "oyster sauce", 3.79 ],
 [ "ground black pepper", 4.19],
 [ "snow peas", 4.99],
 [ "broccoli", 1.89],
 [ "asian sesame oil", 4.99],
 [ "baby corn", 2.09],
 [ "napa cabbage", 3.59],
 [ "zucchini", 5.99],
 [ "fresh mushrooms", 2.59],
 [ "gai lan", 5.89],
 [ "rice vinegar", 3.99],
 [ "hoisin sauce", 4.59],
 [ "ground turkey", 7.18],
 [ "white wine", 10.59],
 [ "phyllo dough", 4.89],
 [ "sweet and sour sauce", 2.99]
]

ingredient_list.each do |ingredient, price|
  Ingredients.create( ingredient: ingredient, price: price)
end
